#include "Core/Log.h"
#include "GUI/FLTK/API.h"

// TODO: ADD SUPPORT FOR UTF-8
// TODO: REPLACE USER INPUT WITH DROP DOWN MENUS
// TODO: ADD PADDING TO ALL LAYERS / BOX AREAS
// TODO: ADD THREAD FOR MULTIPLE INPUT POLLING OR SIMPLY REMOVE CONSOLE FROM RELEASE
// TODO: ADD COMMENTS
// TODO: ADD README / DOCUMENTATION

// FOR CHECKING DAYS UNTIL BIRTHDAY:
// //https://calculat.io/en/date

int main(int argc, char *argv[])
{
   CLI::Log::Init();
   FLTKAPI::Init(635, 530, "Window");

   return 0;
}